export const CATEGORY = 'CATEGORY';
export const MENU_MODAL = 'MENU_MODAL';
export const SETTING_MODAL = 'SETTING_MODAL';
export const CATEGORY_INFO = 'CATEGORY_INFO';
export const RESET_CATEGORYWISE_DATA = 'RESET_CATEGORYWISE_DATA'
export const BUY_PRO_MODEL = 'BUY_PRO_MODEL';
export const SETTING_OPTION = 'SETTING_OPTION'
